name: publish

on: 
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'tag name'     
        required: true

jobs:
  android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install NDK
        run: |
          cd ~
          wget -O NDK -q https://dl.google.com/android/repository/android-ndk-r21b-linux-x86_64.zip
          sudo apt install unzip -y
          unzip -q NDK
          ANDROID_NDK_HOME=$(pwd)/android-ndk-r21b
      - name: Build
        run: |
          cd build
          ./make_android_lua54.sh
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          path: ./build/plugin_lua54/**/*
          name: plugin_lua54
          

  publish:
    runs-on: ubuntu-latest
    needs: [android]
    steps:
      - uses: actions/download-artifact@v1
        with:
          name: plugin_lua54
          path: plugin_lua54/
          
      - name: Create Release Asset
        run: |
          cd plugin_lua54/ && tar cvfz ../lua54_${{ github.event.inputs.tag_name }}.tgz Plugins && cd -
          
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.inputs.tag_name }}
          release_name: Tag:${{ github.event.inputs.tag_name }}
          draft: false
          prerelease: false
          
      - name: Upload lua54 Plugins
        #id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./lua54_${{ github.event.inputs.tag_name }}.tgz
          asset_name: lua54_${{ github.event.inputs.tag_name }}.tgz
          asset_content_type: application/tgz
   
